apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: minimal
  hub: docker.io/istio
  tag: 1.18.0-alpha.0
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      multiCluster:
        clusterName: sidecar-cluster
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
      namespace: istio-system